application: kofapro
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png
- url: /css
  static_dir: static/css
- url: /.*
  script: main.py
