from google.appengine.ext import db

class Csapi(db.Model):
  datum           = db.DateProperty()
  aru             = db.StringProperty()
  vamhazkrt_min   = db.IntegerProperty()
  vamhazkrt_med   = db.IntegerProperty()
  vamhazkrt_max   = db.IntegerProperty()
  vamhazkrt_msg   = db.StringProperty()
  fehervariut_min = db.IntegerProperty()
  fehervariut_med = db.IntegerProperty()
  fehervariut_max = db.IntegerProperty()
  fehervariut_msg = db.StringProperty()
  korhazutca_min  = db.IntegerProperty()
  korhazutca_med  = db.IntegerProperty()
  korhazutca_max  = db.IntegerProperty()
  korhazutca_msg  = db.StringProperty()
  rakocziter_min  = db.IntegerProperty()
  rakocziter_med  = db.IntegerProperty()
  rakocziter_max  = db.IntegerProperty()
  rakocziter_msg  = db.StringProperty()
  vamhazkrt_min   = db.IntegerProperty()
  vamhazkrt_med   = db.IntegerProperty()
  vamhazkrt_max   = db.IntegerProperty()
  vamhazkrt_msg   = db.StringProperty()
